# -*- coding: utf-8 -*-
"""
Multilingual realisation lexicon for BHARAT-SCAM-X.

Nine varieties:
  en      English
  hi      Hindi (Devanagari)
  hi_Latn Hindi (Roman transliteration)
  te      Telugu (Telugu script)
  te_Latn Telugu (Roman transliteration)
  ta      Tamil (Tamil script)
  kn      Kannada (Kannada script)
  cm_hi   English-Hindi code-mixed (Roman)
  cm_te   English-Telugu code-mixed (Roman)

Each slot is realised independently, so a signature composes into a message.
This is a *constructed probe corpus* in the tradition of SCAN, COGS and
CheckList: it measures representational behaviour, not field prevalence.
"""

LANGS = ["en", "hi", "hi_Latn", "te", "te_Latn", "ta", "kn", "cm_hi", "cm_te"]

SCRIPTS = {
    "en": "Latin", "hi": "Devanagari", "hi_Latn": "Latin",
    "te": "Telugu", "te_Latn": "Latin", "ta": "Tamil", "kn": "Kannada",
    "cm_hi": "Latin", "cm_te": "Latin",
}

# ---------------------------------------------------------------------------
# ACTOR prefixes
# ---------------------------------------------------------------------------
ACTOR_PREFIX = {
    "en": {
        "bank": ["SBI Alert:", "HDFC Bank:", "Dear customer,", "Bank notice:"],
        "telecom": ["Airtel:", "Jio notice:", "Dear subscriber,"],
        "government_police": ["Cyber Cell:", "Police Dept:", "Income Tax Dept:"],
        "courier_logistics": ["India Post:", "Courier update:", "Delivery team:"],
        "employer_recruiter": ["HR Team:", "Recruitment:", "Hiring desk:"],
        "ecommerce_platform": ["Order update:", "Support team:", "Customer care:"],
        "known_person": ["Hi, it's me.", "Beta,", "Hello dear,"],
        "utility_provider": ["Electricity Board:", "Power dept:"],
        "tech_support": ["Technical support:", "Helpdesk:"],
        "investment_platform": ["Trading desk:", "Wealth team:"],
    },
    "hi": {
        "bank": ["एसबीआई सूचना:", "बैंक सूचना:", "प्रिय ग्राहक,"],
        "telecom": ["एयरटेल:", "प्रिय उपभोक्ता,"],
        "government_police": ["साइबर सेल:", "पुलिस विभाग:", "आयकर विभाग:"],
        "courier_logistics": ["डाक विभाग:", "कूरियर सूचना:"],
        "employer_recruiter": ["एचआर टीम:", "भर्ती विभाग:"],
        "ecommerce_platform": ["ऑर्डर सूचना:", "ग्राहक सेवा:"],
        "known_person": ["बेटा,", "नमस्ते,"],
        "utility_provider": ["बिजली विभाग:", "विद्युत बोर्ड:"],
        "tech_support": ["तकनीकी सहायता:", "हेल्पडेस्क:"],
        "investment_platform": ["ट्रेडिंग डेस्क:", "निवेश टीम:"],
    },
    "hi_Latn": {
        "bank": ["SBI Suchna:", "Bank notice:", "Priya grahak,"],
        "telecom": ["Airtel:", "Priya upbhokta,"],
        "government_police": ["Cyber Cell:", "Police vibhag:", "Aaykar vibhag:"],
        "courier_logistics": ["Dak vibhag:", "Courier suchna:"],
        "employer_recruiter": ["HR team:", "Bharti vibhag:"],
        "ecommerce_platform": ["Order suchna:", "Grahak seva:"],
        "known_person": ["Beta,", "Namaste,"],
        "utility_provider": ["Bijli vibhag:", "Vidyut board:"],
        "tech_support": ["Takniki sahayata:", "Helpdesk:"],
        "investment_platform": ["Trading desk:", "Nivesh team:"],
    },
    "te": {
        "bank": ["ఎస్‌బిఐ సమాచారం:", "బ్యాంక్ నోటీసు:", "ప్రియమైన కస్టమర్,"],
        "telecom": ["ఎయిర్‌టెల్:", "ప్రియమైన వినియోగదారు,"],
        "government_police": ["సైబర్ సెల్:", "పోలీస్ శాఖ:", "ఆదాయపు పన్ను శాఖ:"],
        "courier_logistics": ["పోస్టల్ శాఖ:", "కొరియర్ సమాచారం:"],
        "employer_recruiter": ["హెచ్‌ఆర్ టీమ్:", "నియామక విభాగం:"],
        "ecommerce_platform": ["ఆర్డర్ సమాచారం:", "కస్టమర్ కేర్:"],
        "known_person": ["బాబు,", "నమస్తే,"],
        "utility_provider": ["విద్యుత్ శాఖ:", "కరెంట్ బోర్డు:"],
        "tech_support": ["సాంకేతిక సహాయం:", "హెల్ప్‌డెస్క్:"],
        "investment_platform": ["ట్రేడింగ్ డెస్క్:", "పెట్టుబడి టీమ్:"],
    },
    "te_Latn": {
        "bank": ["SBI samacharam:", "Bank notice:", "Priyamaina customer,"],
        "telecom": ["Airtel:", "Priyamaina viniyogadaru,"],
        "government_police": ["Cyber cell:", "Police shakha:", "Aadayapu pannu shakha:"],
        "courier_logistics": ["Postal shakha:", "Courier samacharam:"],
        "employer_recruiter": ["HR team:", "Niyamaka vibhagam:"],
        "ecommerce_platform": ["Order samacharam:", "Customer care:"],
        "known_person": ["Babu,", "Namaste,"],
        "utility_provider": ["Vidyut shakha:", "Current board:"],
        "tech_support": ["Sanketika sahayam:", "Helpdesk:"],
        "investment_platform": ["Trading desk:", "Pettubadi team:"],
    },
    "ta": {
        "bank": ["எஸ்பிஐ அறிவிப்பு:", "வங்கி அறிவிப்பு:", "அன்புள்ள வாடிக்கையாளரே,"],
        "telecom": ["ஏர்டெல்:", "அன்புள்ள சந்தாதாரரே,"],
        "government_police": ["சைபர் பிரிவு:", "காவல் துறை:", "வருமான வரித் துறை:"],
        "courier_logistics": ["அஞ்சல் துறை:", "கூரியர் அறிவிப்பு:"],
        "employer_recruiter": ["எச்ஆர் குழு:", "பணியமர்த்தல் பிரிவு:"],
        "ecommerce_platform": ["ஆர்டர் அறிவிப்பு:", "வாடிக்கையாளர் சேவை:"],
        "known_person": ["கண்ணா,", "வணக்கம்,"],
        "utility_provider": ["மின்சார வாரியம்:", "மின் துறை:"],
        "tech_support": ["தொழில்நுட்ப உதவி:", "உதவி மையம்:"],
        "investment_platform": ["டிரேடிங் டெஸ்க்:", "முதலீட்டுக் குழு:"],
    },
    "kn": {
        "bank": ["ಎಸ್‌ಬಿಐ ಸೂಚನೆ:", "ಬ್ಯಾಂಕ್ ಸೂಚನೆ:", "ಆತ್ಮೀಯ ಗ್ರಾಹಕರೇ,"],
        "telecom": ["ಏರ್‌ಟೆಲ್:", "ಆತ್ಮೀಯ ಚಂದಾದಾರರೇ,"],
        "government_police": ["ಸೈಬರ್ ಸೆಲ್:", "ಪೊಲೀಸ್ ಇಲಾಖೆ:", "ಆದಾಯ ತೆರಿಗೆ ಇಲಾಖೆ:"],
        "courier_logistics": ["ಅಂಚೆ ಇಲಾಖೆ:", "ಕೊರಿಯರ್ ಸೂಚನೆ:"],
        "employer_recruiter": ["ಎಚ್‌ಆರ್ ತಂಡ:", "ನೇಮಕಾತಿ ವಿಭಾಗ:"],
        "ecommerce_platform": ["ಆರ್ಡರ್ ಸೂಚನೆ:", "ಗ್ರಾಹಕ ಸೇವೆ:"],
        "known_person": ["ಮಗು,", "ನಮಸ್ಕಾರ,"],
        "utility_provider": ["ವಿದ್ಯುತ್ ಮಂಡಳಿ:", "ವಿದ್ಯುತ್ ಇಲಾಖೆ:"],
        "tech_support": ["ತಾಂತ್ರಿಕ ಸಹಾಯ:", "ಸಹಾಯ ಕೇಂದ್ರ:"],
        "investment_platform": ["ಟ್ರೇಡಿಂಗ್ ಡೆಸ್ಕ್:", "ಹೂಡಿಕೆ ತಂಡ:"],
    },
    "cm_hi": {
        "bank": ["SBI alert:", "Bank se notice:", "Dear customer,"],
        "telecom": ["Airtel:", "Dear user,"],
        "government_police": ["Cyber cell se:", "Police dept:", "IT dept:"],
        "courier_logistics": ["Courier update:", "Post office se:"],
        "employer_recruiter": ["HR team:", "Job desk:"],
        "ecommerce_platform": ["Order update:", "Customer care:"],
        "known_person": ["Beta,", "Hi,"],
        "utility_provider": ["Bijli board:", "Power dept:"],
        "tech_support": ["Tech support:", "Helpdesk:"],
        "investment_platform": ["Trading desk:", "Investment team:"],
    },
    "cm_te": {
        "bank": ["SBI alert:", "Bank notice:", "Dear customer,"],
        "telecom": ["Airtel:", "Dear user,"],
        "government_police": ["Cyber cell nunchi:", "Police dept:", "IT dept:"],
        "courier_logistics": ["Courier update:", "Post office nunchi:"],
        "employer_recruiter": ["HR team:", "Job desk:"],
        "ecommerce_platform": ["Order update:", "Customer care:"],
        "known_person": ["Babu,", "Hi,"],
        "utility_provider": ["Current board:", "Power dept:"],
        "tech_support": ["Tech support:", "Helpdesk:"],
        "investment_platform": ["Trading desk:", "Investment team:"],
    },
}

# ---------------------------------------------------------------------------
# PRETEXT clauses
# ---------------------------------------------------------------------------
PRETEXT_CLAUSE = {
    "en": {
        "kyc_expiry": ["Your KYC has expired.", "KYC verification is pending on your account.",
                       "Your KYC document needs re-submission."],
        "account_suspension": ["Your account will be blocked today.", "Your account has been temporarily suspended.",
                               "Account access will be withdrawn shortly."],
        "legal_action": ["A case has been registered against your Aadhaar.",
                         "An arrest warrant has been issued in your name.",
                         "Your number is linked to an illegal transaction."],
        "parcel_held": ["Your parcel is held at customs.", "Your delivery could not be completed.",
                        "A package addressed to you is pending clearance."],
        "bill_overdue": ["Your electricity bill is unpaid.", "Your connection will be disconnected tonight."],
        "job_offer": ["You are selected for a part-time work-from-home role.",
                      "Your profile is shortlisted for daily payout tasks."],
        "prize_win": ["You have won a lucky draw prize of Rs 25,000.",
                      "Congratulations! Your number won our monthly contest."],
        "refund_due": ["A refund of Rs 4,999 is pending for your order.",
                       "Your cancelled order refund is ready to be credited."],
        "investment_return": ["Your investment has returned 38% this week.",
                              "Guaranteed daily profit is available on your account."],
        "emergency_help": ["I am in hospital and need money urgently.",
                           "I lost my wallet while travelling and need help."],
    },
    "hi": {
        "kyc_expiry": ["आपका केवाईसी समाप्त हो गया है।", "आपके खाते पर केवाईसी सत्यापन बाकी है।",
                       "आपका केवाईसी दस्तावेज़ फिर से जमा करना होगा।"],
        "account_suspension": ["आपका खाता आज ब्लॉक कर दिया जाएगा।", "आपका खाता अस्थायी रूप से निलंबित है।",
                               "खाते की सुविधा शीघ्र बंद हो जाएगी।"],
        "legal_action": ["आपके आधार पर मामला दर्ज हुआ है।", "आपके नाम पर गिरफ्तारी वारंट जारी हुआ है।",
                         "आपका नंबर अवैध लेनदेन से जुड़ा है।"],
        "parcel_held": ["आपका पार्सल सीमा शुल्क पर रुका है।", "आपकी डिलीवरी पूरी नहीं हो सकी।"],
        "bill_overdue": ["आपका बिजली बिल बकाया है।", "आज रात आपका कनेक्शन काट दिया जाएगा।"],
        "job_offer": ["आप घर से काम करने वाली नौकरी के लिए चुने गए हैं।",
                      "आपकी प्रोफ़ाइल दैनिक भुगतान कार्य के लिए चुनी गई है।"],
        "prize_win": ["आपने 25,000 रुपये का लकी ड्रॉ इनाम जीता है।", "बधाई हो! आपका नंबर विजेता है।"],
        "refund_due": ["आपके ऑर्डर का 4,999 रुपये रिफंड बाकी है।", "आपका रिफंड जमा होने के लिए तैयार है।"],
        "investment_return": ["आपके निवेश पर इस हफ्ते 38% लाभ हुआ है।", "आपके खाते पर रोज़ाना मुनाफ़ा उपलब्ध है।"],
        "emergency_help": ["मैं अस्पताल में हूँ और तुरंत पैसे चाहिए।", "यात्रा में मेरा पर्स खो गया, मदद चाहिए।"],
    },
    "hi_Latn": {
        "kyc_expiry": ["Aapka KYC samapt ho gaya hai.", "Aapke khate par KYC verification baaki hai.",
                       "Aapka KYC document dobara jama karna hoga."],
        "account_suspension": ["Aapka khata aaj block kar diya jayega.", "Aapka khata asthayi roop se nilambit hai.",
                               "Khate ki suvidha jaldi band ho jayegi."],
        "legal_action": ["Aapke Aadhaar par mamla darj hua hai.", "Aapke naam par giraftari warrant jari hua hai.",
                         "Aapka number avaidh len-den se juda hai."],
        "parcel_held": ["Aapka parcel customs par ruka hai.", "Aapki delivery poori nahi ho saki."],
        "bill_overdue": ["Aapka bijli bill bakaya hai.", "Aaj raat aapka connection kat diya jayega."],
        "job_offer": ["Aap ghar se kaam karne wali naukri ke liye chune gaye hain.",
                      "Aapki profile dainik bhugtan kaary ke liye chuni gayi hai."],
        "prize_win": ["Aapne 25,000 rupaye ka lucky draw inaam jeeta hai.", "Badhai ho! Aapka number vijeta hai."],
        "refund_due": ["Aapke order ka 4,999 rupaye refund baaki hai.", "Aapka refund jama hone ke liye taiyar hai."],
        "investment_return": ["Aapke nivesh par is hafte 38% labh hua hai.", "Aapke khate par rozana munafa uplabdh hai."],
        "emergency_help": ["Main hospital mein hoon aur turant paise chahiye.", "Yatra mein mera purse kho gaya, madad chahiye."],
    },
    "te": {
        "kyc_expiry": ["మీ కేవైసీ గడువు ముగిసింది.", "మీ ఖాతాలో కేవైసీ ధృవీకరణ పెండింగ్‌లో ఉంది.",
                       "మీ కేవైసీ పత్రం మళ్లీ సమర్పించాలి."],
        "account_suspension": ["మీ ఖాతా ఈరోజు బ్లాక్ అవుతుంది.", "మీ ఖాతా తాత్కాలికంగా నిలిపివేయబడింది.",
                               "ఖాతా సదుపాయం త్వరలో నిలిచిపోతుంది."],
        "legal_action": ["మీ ఆధార్‌పై కేసు నమోదైంది.", "మీ పేరుపై అరెస్ట్ వారెంట్ జారీ అయింది.",
                         "మీ నంబర్ అక్రమ లావాదేవీతో ముడిపడి ఉంది."],
        "parcel_held": ["మీ పార్సెల్ కస్టమ్స్‌లో ఆగిపోయింది.", "మీ డెలివరీ పూర్తి కాలేదు."],
        "bill_overdue": ["మీ కరెంటు బిల్లు బకాయి ఉంది.", "ఈ రాత్రి మీ కనెక్షన్ తొలగించబడుతుంది."],
        "job_offer": ["ఇంటి నుండి పని చేసే ఉద్యోగానికి మీరు ఎంపికయ్యారు.",
                      "రోజువారీ చెల్లింపు పనులకు మీ ప్రొఫైల్ ఎంపికైంది."],
        "prize_win": ["మీరు 25,000 రూపాయల లక్కీ డ్రా బహుమతి గెలుచుకున్నారు.", "అభినందనలు! మీ నంబర్ విజేత."],
        "refund_due": ["మీ ఆర్డర్‌కు 4,999 రూపాయల రీఫండ్ పెండింగ్‌లో ఉంది.", "మీ రీఫండ్ జమ చేయడానికి సిద్ధంగా ఉంది."],
        "investment_return": ["ఈ వారం మీ పెట్టుబడిపై 38% లాభం వచ్చింది.", "మీ ఖాతాలో రోజువారీ లాభం అందుబాటులో ఉంది."],
        "emergency_help": ["నేను ఆసుపత్రిలో ఉన్నాను, వెంటనే డబ్బు కావాలి.", "ప్రయాణంలో నా పర్సు పోయింది, సహాయం కావాలి."],
    },
    "te_Latn": {
        "kyc_expiry": ["Mee KYC gaduvu mugisindi.", "Mee khatalo KYC dhruvikarana pending lo undi.",
                       "Mee KYC patram malli samarpinchali."],
        "account_suspension": ["Mee khata eeroju block avutundi.", "Mee khata tatkalikanga nilipiveyabadindi.",
                               "Khata sadupayam tvaralo nilichipotundi."],
        "legal_action": ["Mee Aadhaar pai case namodaindi.", "Mee peruta arrest warrant jari ayindi.",
                         "Mee number akrama lavadevito mudipadi undi."],
        "parcel_held": ["Mee parcel customs lo agipoyindi.", "Mee delivery poorthi kaledu."],
        "bill_overdue": ["Mee currentu billu bakayi undi.", "Ee ratri mee connection tolaginchabadutundi."],
        "job_offer": ["Inti nunchi pani chese udyoganiki meeru empikayyaru.",
                      "Rojuvari chellimpu panulaku mee profile empikaindi."],
        "prize_win": ["Meeru 25,000 rupayala lucky draw bahumati gelichukunnaru.", "Abhinandanalu! Mee number vijeta."],
        "refund_due": ["Mee order ku 4,999 rupayala refund pending lo undi.", "Mee refund jama cheyadaniki siddhanga undi."],
        "investment_return": ["Ee varam mee pettubadi pai 38% labham vachindi.", "Mee khatalo rojuvari labham andubatulo undi."],
        "emergency_help": ["Nenu asupatrilo unnanu, ventane dabbu kavali.", "Prayanamlo naa parsu poyindi, sahayam kavali."],
    },
    "ta": {
        "kyc_expiry": ["உங்கள் கேஒய்சி காலாவதியாகிவிட்டது.", "உங்கள் கணக்கில் கேஒய்சி சரிபார்ப்பு நிலுவையில் உள்ளது.",
                       "உங்கள் கேஒய்சி ஆவணத்தை மீண்டும் சமர்ப்பிக்க வேண்டும்."],
        "account_suspension": ["உங்கள் கணக்கு இன்று முடக்கப்படும்.", "உங்கள் கணக்கு தற்காலிகமாக இடைநிறுத்தப்பட்டுள்ளது.",
                               "கணக்கு வசதி விரைவில் நிறுத்தப்படும்."],
        "legal_action": ["உங்கள் ஆதார் மீது வழக்கு பதிவு செய்யப்பட்டுள்ளது.", "உங்கள் பெயரில் கைது வாரண்ட் பிறப்பிக்கப்பட்டுள்ளது.",
                         "உங்கள் எண் சட்டவிரோத பரிவர்த்தனையுடன் தொடர்புடையது."],
        "parcel_held": ["உங்கள் பார்சல் சுங்கத்தில் நிறுத்தப்பட்டுள்ளது.", "உங்கள் டெலிவரி முடிக்க முடியவில்லை."],
        "bill_overdue": ["உங்கள் மின் கட்டணம் நிலுவையில் உள்ளது.", "இன்றிரவு உங்கள் இணைப்பு துண்டிக்கப்படும்."],
        "job_offer": ["வீட்டிலிருந்து வேலை செய்யும் பணிக்கு நீங்கள் தேர்ந்தெடுக்கப்பட்டுள்ளீர்கள்.",
                      "தினசரி ஊதியப் பணிகளுக்கு உங்கள் சுயவிவரம் தேர்வாகியுள்ளது."],
        "prize_win": ["நீங்கள் 25,000 ரூபாய் லக்கி டிரா பரிசு வென்றுள்ளீர்கள்.", "வாழ்த்துக்கள்! உங்கள் எண் வெற்றி பெற்றது."],
        "refund_due": ["உங்கள் ஆர்டருக்கு 4,999 ரூபாய் பணத்திரும்பம் நிலுவையில் உள்ளது.", "உங்கள் பணத்திரும்பம் வரவு வைக்கத் தயாராக உள்ளது."],
        "investment_return": ["இந்த வாரம் உங்கள் முதலீட்டில் 38% லாபம் கிடைத்துள்ளது.", "உங்கள் கணக்கில் தினசரி லாபம் கிடைக்கிறது."],
        "emergency_help": ["நான் மருத்துவமனையில் இருக்கிறேன், உடனே பணம் வேண்டும்.", "பயணத்தில் என் பணப்பை தொலைந்துவிட்டது, உதவி வேண்டும்."],
    },
    "kn": {
        "kyc_expiry": ["ನಿಮ್ಮ ಕೆವೈಸಿ ಅವಧಿ ಮುಗಿದಿದೆ.", "ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ಕೆವೈಸಿ ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ.",
                       "ನಿಮ್ಮ ಕೆವೈಸಿ ದಾಖಲೆಯನ್ನು ಮತ್ತೆ ಸಲ್ಲಿಸಬೇಕು."],
        "account_suspension": ["ನಿಮ್ಮ ಖಾತೆ ಇಂದು ಬ್ಲಾಕ್ ಆಗುತ್ತದೆ.", "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ತಾತ್ಕಾಲಿಕವಾಗಿ ಅಮಾನತು ಮಾಡಲಾಗಿದೆ.",
                               "ಖಾತೆ ಸೌಲಭ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಸ್ಥಗಿತವಾಗುತ್ತದೆ."],
        "legal_action": ["ನಿಮ್ಮ ಆಧಾರ್ ಮೇಲೆ ಪ್ರಕರಣ ದಾಖಲಾಗಿದೆ.", "ನಿಮ್ಮ ಹೆಸರಿನಲ್ಲಿ ಬಂಧನ ವಾರಂಟ್ ಹೊರಡಿಸಲಾಗಿದೆ.",
                         "ನಿಮ್ಮ ಸಂಖ್ಯೆ ಅಕ್ರಮ ವಹಿವಾಟಿಗೆ ಸಂಬಂಧಿಸಿದೆ."],
        "parcel_held": ["ನಿಮ್ಮ ಪಾರ್ಸೆಲ್ ಕಸ್ಟಮ್ಸ್‌ನಲ್ಲಿ ನಿಂತಿದೆ.", "ನಿಮ್ಮ ಡೆಲಿವರಿ ಪೂರ್ಣಗೊಳ್ಳಲಿಲ್ಲ."],
        "bill_overdue": ["ನಿಮ್ಮ ವಿದ್ಯುತ್ ಬಿಲ್ ಬಾಕಿ ಇದೆ.", "ಇಂದು ರಾತ್ರಿ ನಿಮ್ಮ ಸಂಪರ್ಕ ಕಡಿತಗೊಳ್ಳುತ್ತದೆ."],
        "job_offer": ["ಮನೆಯಿಂದ ಕೆಲಸ ಮಾಡುವ ಉದ್ಯೋಗಕ್ಕೆ ನೀವು ಆಯ್ಕೆಯಾಗಿದ್ದೀರಿ.",
                      "ದಿನನಿತ್ಯದ ಪಾವತಿ ಕೆಲಸಗಳಿಗೆ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಆಯ್ಕೆಯಾಗಿದೆ."],
        "prize_win": ["ನೀವು 25,000 ರೂಪಾಯಿ ಲಕ್ಕಿ ಡ್ರಾ ಬಹುಮಾನ ಗೆದ್ದಿದ್ದೀರಿ.", "ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಸಂಖ್ಯೆ ವಿಜೇತ."],
        "refund_due": ["ನಿಮ್ಮ ಆರ್ಡರ್‌ಗೆ 4,999 ರೂಪಾಯಿ ಮರುಪಾವತಿ ಬಾಕಿ ಇದೆ.", "ನಿಮ್ಮ ಮರುಪಾವತಿ ಜಮಾ ಮಾಡಲು ಸಿದ್ಧವಾಗಿದೆ."],
        "investment_return": ["ಈ ವಾರ ನಿಮ್ಮ ಹೂಡಿಕೆಯ ಮೇಲೆ 38% ಲಾಭ ಬಂದಿದೆ.", "ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ದೈನಂದಿನ ಲಾಭ ಲಭ್ಯವಿದೆ."],
        "emergency_help": ["ನಾನು ಆಸ್ಪತ್ರೆಯಲ್ಲಿದ್ದೇನೆ, ತಕ್ಷಣ ಹಣ ಬೇಕು.", "ಪ್ರಯಾಣದಲ್ಲಿ ನನ್ನ ಪರ್ಸ್ ಕಳೆದುಹೋಯಿತು, ಸಹಾಯ ಬೇಕು."],
    },
    "cm_hi": {
        "kyc_expiry": ["Aapka KYC expire ho gaya hai.", "Account par KYC verification pending hai."],
        "account_suspension": ["Aapka account block ho jayega.", "Account temporarily suspend kar diya gaya hai."],
        "legal_action": ["Aapke Aadhaar par case register hua hai.", "Aapke naam par arrest warrant issue hua hai."],
        "parcel_held": ["Aapka parcel customs par hold hai.", "Delivery complete nahi ho payi."],
        "bill_overdue": ["Aapka electricity bill pending hai.", "Aaj raat connection disconnect ho jayega."],
        "job_offer": ["Aap work from home part-time job ke liye select hue hain.",
                      "Daily payout task ke liye aapki profile shortlist hui hai."],
        "prize_win": ["Aapne Rs 25,000 ka lucky draw prize jeeta hai.", "Congrats! Aapka number winner hai."],
        "refund_due": ["Aapke order ka Rs 4,999 refund pending hai.", "Refund credit hone ke liye ready hai."],
        "investment_return": ["Is week aapke investment par 38% return mila hai.", "Daily guaranteed profit available hai."],
        "emergency_help": ["Main hospital mein hoon, urgent paise chahiye.", "Travel mein wallet kho gaya, help chahiye."],
    },
    "cm_te": {
        "kyc_expiry": ["Mee KYC expire ayindi.", "Account lo KYC verification pending undi."],
        "account_suspension": ["Mee account block avutundi.", "Account temporary ga suspend chesaru."],
        "legal_action": ["Mee Aadhaar pai case register ayindi.", "Mee peruta arrest warrant issue ayindi."],
        "parcel_held": ["Mee parcel customs lo hold lo undi.", "Delivery complete kaledu."],
        "bill_overdue": ["Mee current bill pending undi.", "Ee ratri connection disconnect avutundi."],
        "job_offer": ["Meeru work from home part-time job ki select ayyaru.",
                      "Daily payout tasks ki mee profile shortlist ayindi."],
        "prize_win": ["Meeru Rs 25,000 lucky draw prize gelicharu.", "Congrats! Mee number winner."],
        "refund_due": ["Mee order ki Rs 4,999 refund pending undi.", "Refund credit cheyadaniki ready ga undi."],
        "investment_return": ["Ee week mee investment pai 38% return vachindi.", "Daily guaranteed profit available undi."],
        "emergency_help": ["Nenu hospital lo unnanu, urgent ga dabbu kavali.", "Travel lo wallet poyindi, help kavali."],
    },
}

# ---------------------------------------------------------------------------
# ACTION clauses, keyed by (action, target)
# ---------------------------------------------------------------------------
ACTION_CLAUSE = {
    "en": {
        ("share_code", "otp"): ["Share the OTP sent to your phone.", "Reply with the 6-digit OTP to verify.",
                                "Tell us the OTP to complete verification."],
        ("click_link", "account_credentials"): ["Click http://bit.ly/kyc-verify and log in.",
                                                "Update now at http://tinyurl.com/acct-fix",
                                                "Verify at http://bit.ly/re-kyc using your net banking password."],
        ("make_payment", "funds"): ["Pay Rs 4,500 to clear this.", "Transfer Rs 4,500 to UPI id settle@okaxis.",
                                    "Deposit Rs 4,500 immediately to avoid further action."],
        ("call_number", "none"): ["Call 9876543210 now.", "Contact our officer at 9876543210 immediately."],
        ("install_app", "device_control"): ["Install AnyDesk and share the 9-digit code.",
                                            "Download the support app from http://bit.ly/fix-app and give access."],
        ("scan_qr", "upi_pin"): ["Scan the QR we send and enter your UPI PIN to receive it.",
                                 "Scan this QR code and enter your PIN to collect the amount."],
    },
    "hi": {
        ("share_code", "otp"): ["आपके फ़ोन पर भेजा गया ओटीपी साझा करें।", "सत्यापन के लिए 6 अंकों का ओटीपी बताएं।",
                                "ओटीपी बताइए ताकि सत्यापन पूरा हो।"],
        ("click_link", "account_credentials"): ["http://bit.ly/kyc-verify पर जाकर लॉगिन करें।",
                                                "अभी http://tinyurl.com/acct-fix पर अपडेट करें।"],
        ("make_payment", "funds"): ["4,500 रुपये का भुगतान करें।", "settle@okaxis पर 4,500 रुपये भेजें।",
                                    "कार्रवाई से बचने के लिए तुरंत 4,500 रुपये जमा करें।"],
        ("call_number", "none"): ["अभी 9876543210 पर कॉल करें।", "हमारे अधिकारी से 9876543210 पर संपर्क करें।"],
        ("install_app", "device_control"): ["AnyDesk इंस्टॉल करें और 9 अंकों का कोड बताएं।",
                                            "http://bit.ly/fix-app से ऐप डाउनलोड करें और एक्सेस दें।"],
        ("scan_qr", "upi_pin"): ["भेजा गया क्यूआर स्कैन करें और यूपीआई पिन डालें।",
                                 "क्यूआर कोड स्कैन कर पिन डालें ताकि राशि मिले।"],
    },
    "hi_Latn": {
        ("share_code", "otp"): ["Aapke phone par bheja gaya OTP share karein.", "Verification ke liye 6 ank ka OTP bataiye.",
                                "OTP bataiye taki verification poora ho."],
        ("click_link", "account_credentials"): ["http://bit.ly/kyc-verify par jaakar login karein.",
                                                "Abhi http://tinyurl.com/acct-fix par update karein."],
        ("make_payment", "funds"): ["4,500 rupaye ka bhugtan karein.", "settle@okaxis par 4,500 rupaye bhejein.",
                                    "Karrwai se bachne ke liye turant 4,500 rupaye jama karein."],
        ("call_number", "none"): ["Abhi 9876543210 par call karein.", "Hamare adhikari se 9876543210 par sampark karein."],
        ("install_app", "device_control"): ["AnyDesk install karein aur 9 ank ka code bataiye.",
                                            "http://bit.ly/fix-app se app download karein aur access dein."],
        ("scan_qr", "upi_pin"): ["Bheja gaya QR scan karein aur UPI PIN daalein.",
                                 "QR code scan kar PIN daalein taki rashi mile."],
    },
    "te": {
        ("share_code", "otp"): ["మీ ఫోన్‌కు వచ్చిన ఓటీపీ చెప్పండి.", "ధృవీకరణ కోసం 6 అంకెల ఓటీపీ పంపండి.",
                                "ఓటీపీ చెబితే ధృవీకరణ పూర్తవుతుంది."],
        ("click_link", "account_credentials"): ["http://bit.ly/kyc-verify లో లాగిన్ అవ్వండి.",
                                                "ఇప్పుడే http://tinyurl.com/acct-fix లో అప్‌డేట్ చేయండి."],
        ("make_payment", "funds"): ["4,500 రూపాయలు చెల్లించండి.", "settle@okaxis కు 4,500 రూపాయలు పంపండి.",
                                    "చర్యలు తప్పించుకోవడానికి వెంటనే 4,500 రూపాయలు జమ చేయండి."],
        ("call_number", "none"): ["ఇప్పుడే 9876543210 కు కాల్ చేయండి.", "మా అధికారిని 9876543210 లో సంప్రదించండి."],
        ("install_app", "device_control"): ["AnyDesk ఇన్‌స్టాల్ చేసి 9 అంకెల కోడ్ చెప్పండి.",
                                            "http://bit.ly/fix-app నుండి యాప్ డౌన్‌లోడ్ చేసి యాక్సెస్ ఇవ్వండి."],
        ("scan_qr", "upi_pin"): ["పంపిన క్యూఆర్ స్కాన్ చేసి యూపీఐ పిన్ నమోదు చేయండి.",
                                 "క్యూఆర్ కోడ్ స్కాన్ చేసి పిన్ వేస్తే మొత్తం వస్తుంది."],
    },
    "te_Latn": {
        ("share_code", "otp"): ["Mee phone ki vachina OTP cheppandi.", "Dhruvikarana kosam 6 ankela OTP pampandi.",
                                "OTP chebite verification poorthavutundi."],
        ("click_link", "account_credentials"): ["http://bit.ly/kyc-verify lo login avvandi.",
                                                "Ippude http://tinyurl.com/acct-fix lo update cheyandi."],
        ("make_payment", "funds"): ["4,500 rupayalu chellinchandi.", "settle@okaxis ku 4,500 rupayalu pampandi.",
                                    "Charyalu tappinchukovadaniki ventane 4,500 rupayalu jama cheyandi."],
        ("call_number", "none"): ["Ippude 9876543210 ku call cheyandi.", "Maa adhikarini 9876543210 lo sampradinchandi."],
        ("install_app", "device_control"): ["AnyDesk install chesi 9 ankela code cheppandi.",
                                            "http://bit.ly/fix-app nunchi app download chesi access ivvandi."],
        ("scan_qr", "upi_pin"): ["Pampina QR scan chesi UPI PIN namodu cheyandi.",
                                 "QR code scan chesi PIN veste mottam vastundi."],
    },
    "ta": {
        ("share_code", "otp"): ["உங்கள் தொலைபேசிக்கு வந்த OTP ஐப் பகிரவும்.", "சரிபார்ப்புக்கு 6 இலக்க OTP ஐ அனுப்பவும்.",
                                "OTP சொன்னால் சரிபார்ப்பு முடியும்."],
        ("click_link", "account_credentials"): ["http://bit.ly/kyc-verify இல் உள்நுழையவும்.",
                                                "இப்போதே http://tinyurl.com/acct-fix இல் புதுப்பிக்கவும்."],
        ("make_payment", "funds"): ["4,500 ரூபாய் செலுத்தவும்.", "settle@okaxis க்கு 4,500 ரூபாய் அனுப்பவும்.",
                                    "நடவடிக்கையைத் தவிர்க்க உடனே 4,500 ரூபாய் செலுத்தவும்."],
        ("call_number", "none"): ["இப்போதே 9876543210 ஐ அழைக்கவும்.", "எங்கள் அதிகாரியை 9876543210 இல் தொடர்பு கொள்ளவும்."],
        ("install_app", "device_control"): ["AnyDesk நிறுவி 9 இலக்கக் குறியீட்டைச் சொல்லவும்.",
                                            "http://bit.ly/fix-app இலிருந்து செயலியைப் பதிவிறக்கி அணுகல் கொடுக்கவும்."],
        ("scan_qr", "upi_pin"): ["அனுப்பிய QR ஐ ஸ்கேன் செய்து UPI PIN ஐ உள்ளிடவும்.",
                                 "QR குறியீட்டை ஸ்கேன் செய்து PIN இட்டால் தொகை கிடைக்கும்."],
    },
    "kn": {
        ("share_code", "otp"): ["ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಬಂದ OTP ಹಂಚಿಕೊಳ್ಳಿ.", "ಪರಿಶೀಲನೆಗಾಗಿ 6 ಅಂಕಿಯ OTP ಕಳುಹಿಸಿ.",
                                "OTP ಹೇಳಿದರೆ ಪರಿಶೀಲನೆ ಪೂರ್ಣವಾಗುತ್ತದೆ."],
        ("click_link", "account_credentials"): ["http://bit.ly/kyc-verify ನಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ.",
                                                "ಈಗಲೇ http://tinyurl.com/acct-fix ನಲ್ಲಿ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ."],
        ("make_payment", "funds"): ["4,500 ರೂಪಾಯಿ ಪಾವತಿಸಿ.", "settle@okaxis ಗೆ 4,500 ರೂಪಾಯಿ ಕಳುಹಿಸಿ.",
                                    "ಕ್ರಮ ತಪ್ಪಿಸಲು ತಕ್ಷಣ 4,500 ರೂಪಾಯಿ ಜಮಾ ಮಾಡಿ."],
        ("call_number", "none"): ["ಈಗಲೇ 9876543210 ಗೆ ಕರೆ ಮಾಡಿ.", "ನಮ್ಮ ಅಧಿಕಾರಿಯನ್ನು 9876543210 ನಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ."],
        ("install_app", "device_control"): ["AnyDesk ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿ 9 ಅಂಕಿಯ ಕೋಡ್ ಹೇಳಿ.",
                                            "http://bit.ly/fix-app ನಿಂದ ಆ್ಯಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಪ್ರವೇಶ ಕೊಡಿ."],
        ("scan_qr", "upi_pin"): ["ಕಳುಹಿಸಿದ QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ UPI PIN ನಮೂದಿಸಿ.",
                                 "QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ PIN ಹಾಕಿದರೆ ಮೊತ್ತ ಸಿಗುತ್ತದೆ."],
    },
    "cm_hi": {
        ("share_code", "otp"): ["Phone par aaya OTP share karein.", "Verify karne ke liye 6-digit OTP reply karein."],
        ("click_link", "account_credentials"): ["http://bit.ly/kyc-verify par click karke login karein.",
                                                "Abhi http://tinyurl.com/acct-fix par update kar dein."],
        ("make_payment", "funds"): ["Rs 4,500 pay kar dein.", "settle@okaxis par Rs 4,500 transfer karein."],
        ("call_number", "none"): ["Abhi 9876543210 par call karein.", "Officer se 9876543210 par contact karein."],
        ("install_app", "device_control"): ["AnyDesk install karke 9-digit code share karein.",
                                            "http://bit.ly/fix-app se app download karke access dein."],
        ("scan_qr", "upi_pin"): ["QR scan karke UPI PIN enter karein.", "QR code scan karein aur PIN daalein."],
    },
    "cm_te": {
        ("share_code", "otp"): ["Phone ki vachina OTP share cheyandi.", "Verify cheyadaniki 6-digit OTP reply cheyandi."],
        ("click_link", "account_credentials"): ["http://bit.ly/kyc-verify pai click chesi login avvandi.",
                                                "Ippude http://tinyurl.com/acct-fix lo update cheyandi."],
        ("make_payment", "funds"): ["Rs 4,500 pay cheyandi.", "settle@okaxis ki Rs 4,500 transfer cheyandi."],
        ("call_number", "none"): ["Ippude 9876543210 ki call cheyandi.", "Officer ni 9876543210 lo contact cheyandi."],
        ("install_app", "device_control"): ["AnyDesk install chesi 9-digit code share cheyandi.",
                                            "http://bit.ly/fix-app nunchi app download chesi access ivvandi."],
        ("scan_qr", "upi_pin"): ["QR scan chesi UPI PIN enter cheyandi.", "QR code scan chesi PIN veyandi."],
    },
}

# ---------------------------------------------------------------------------
# URGENCY / tactic intensifiers
# ---------------------------------------------------------------------------
URGENCY = {
    "en": ["Act within 24 hours.", "Immediately.", "Failure to comply will lead to legal action.", ""],
    "hi": ["24 घंटे के भीतर कार्रवाई करें।", "तुरंत।", "न करने पर कानूनी कार्रवाई होगी।", ""],
    "hi_Latn": ["24 ghante ke bheetar karrwai karein.", "Turant.", "Na karne par kanooni karrwai hogi.", ""],
    "te": ["24 గంటల్లోగా స్పందించండి.", "వెంటనే.", "లేకపోతే చట్టపరమైన చర్యలు ఉంటాయి.", ""],
    "te_Latn": ["24 gantallo spandinchandi.", "Ventane.", "Lekapote chattaparamaina charyalu untayi.", ""],
    "ta": ["24 மணி நேரத்திற்குள் செயல்படவும்.", "உடனடியாக.", "இல்லையெனில் சட்ட நடவடிக்கை எடுக்கப்படும்.", ""],
    "kn": ["24 ಗಂಟೆಗಳ ಒಳಗೆ ಕ್ರಮ ಕೈಗೊಳ್ಳಿ.", "ತಕ್ಷಣ.", "ಇಲ್ಲದಿದ್ದರೆ ಕಾನೂನು ಕ್ರಮ ಕೈಗೊಳ್ಳಲಾಗುವುದು.", ""],
    "cm_hi": ["24 hours ke andar karein.", "Turant.", "Warna legal action hoga.", ""],
    "cm_te": ["24 hours lopu cheyandi.", "Ventane.", "Lekapote legal action untundi.", ""],
}

# ---------------------------------------------------------------------------
# REFRAIN clauses -- used to build SEMANTIC FLIPS.
# High lexical overlap with the corresponding ACTION_CLAUSE, opposite
# security semantics.
# ---------------------------------------------------------------------------
REFRAIN_CLAUSE = {
    "en": {
        "otp": ["Never share the OTP sent to your phone with anyone.",
                "Do not reply with the 6-digit OTP to anyone; the bank never asks for it."],
        "account_credentials": ["Never click unknown links or log in with your net banking password.",
                                "Do not enter your password on any link received by SMS."],
        "funds": ["Do not transfer Rs 4,500 to anyone claiming to be us.",
                  "Never deposit money to a UPI id shared over SMS."],
        "none": ["Do not call numbers received in such messages.",
                 "Never contact unknown numbers claiming to be our officers."],
        "device_control": ["Never install AnyDesk or any screen-sharing app on a caller's request.",
                           "Do not download apps from links and never give remote access."],
        "upi_pin": ["Never scan a QR or enter your UPI PIN to receive money.",
                    "Entering your PIN never credits money to you; do not scan such QR codes."],
    },
    "hi": {
        "otp": ["अपने फ़ोन पर आया ओटीपी किसी को न बताएं।",
                "6 अंकों का ओटीपी किसी को न बताएं; बैंक कभी नहीं मांगता।"],
        "account_credentials": ["अनजान लिंक पर क्लिक कर लॉगिन न करें।", "एसएमएस के लिंक पर पासवर्ड न डालें।"],
        "funds": ["हमारे नाम पर मांगने वाले को 4,500 रुपये न भेजें।", "एसएमएस से मिली यूपीआई आईडी पर पैसे न भेजें।"],
        "none": ["ऐसे संदेशों में आए नंबर पर कॉल न करें।", "अधिकारी बताने वाले अनजान नंबर पर संपर्क न करें।"],
        "device_control": ["किसी के कहने पर AnyDesk इंस्टॉल न करें।", "लिंक से ऐप डाउनलोड कर एक्सेस न दें।"],
        "upi_pin": ["पैसे पाने के लिए क्यूआर स्कैन कर पिन कभी न डालें।", "पिन डालने से पैसे नहीं आते; ऐसे क्यूआर न स्कैन करें।"],
    },
    "hi_Latn": {
        "otp": ["Apne phone par aaya OTP kisi ko na batayein.",
                "6 ank ka OTP kisi ko na batayein; bank kabhi nahi maangta."],
        "account_credentials": ["Anjaan link par click kar login na karein.", "SMS ke link par password na daalein."],
        "funds": ["Hamare naam par maangne wale ko 4,500 rupaye na bhejein.", "SMS se mili UPI id par paise na bhejein."],
        "none": ["Aise sandeshon mein aaye number par call na karein.", "Adhikari batane wale anjaan number par sampark na karein."],
        "device_control": ["Kisi ke kehne par AnyDesk install na karein.", "Link se app download kar access na dein."],
        "upi_pin": ["Paise paane ke liye QR scan kar PIN kabhi na daalein.", "PIN daalne se paise nahi aate; aise QR na scan karein."],
    },
    "te": {
        "otp": ["మీ ఫోన్‌కు వచ్చిన ఓటీపీ ఎవరికీ చెప్పవద్దు.",
                "6 అంకెల ఓటీపీ ఎవరికీ చెప్పవద్దు; బ్యాంక్ ఎప్పుడూ అడగదు."],
        "account_credentials": ["తెలియని లింక్‌లపై క్లిక్ చేసి లాగిన్ అవ్వవద్దు.", "ఎస్‌ఎంఎస్ లింక్‌లో పాస్‌వర్డ్ నమోదు చేయవద్దు."],
        "funds": ["మా పేరు చెప్పి అడిగే వారికి 4,500 రూపాయలు పంపవద్దు.", "ఎస్‌ఎంఎస్‌లో వచ్చిన యూపీఐ ఐడీకి డబ్బు పంపవద్దు."],
        "none": ["ఇలాంటి సందేశాల్లోని నంబర్‌కు కాల్ చేయవద్దు.", "అధికారి అని చెప్పే తెలియని నంబర్‌ను సంప్రదించవద్దు."],
        "device_control": ["ఎవరైనా చెప్పినా AnyDesk ఇన్‌స్టాల్ చేయవద్దు.", "లింక్ నుండి యాప్ డౌన్‌లోడ్ చేసి యాక్సెస్ ఇవ్వవద్దు."],
        "upi_pin": ["డబ్బు రావడానికి క్యూఆర్ స్కాన్ చేసి పిన్ ఎప్పుడూ వేయవద్దు.", "పిన్ వేస్తే డబ్బు రాదు; అలాంటి క్యూఆర్ స్కాన్ చేయవద్దు."],
    },
    "te_Latn": {
        "otp": ["Mee phone ki vachina OTP evariki cheppavaddu.",
                "6 ankela OTP evariki cheppavaddu; bank eppudu adagadu."],
        "account_credentials": ["Teliyani link lapai click chesi login avvavaddu.", "SMS link lo password namodu cheyavaddu."],
        "funds": ["Maa peru cheppi adige variki 4,500 rupayalu pampavaddu.", "SMS lo vachina UPI id ki dabbu pampavaddu."],
        "none": ["Ilanti sandeshallo ni number ku call cheyavaddu.", "Adhikari ani cheppe teliyani number ni sampradinchavaddu."],
        "device_control": ["Evaraina cheppina AnyDesk install cheyavaddu.", "Link nunchi app download chesi access ivvavaddu."],
        "upi_pin": ["Dabbu ravadaniki QR scan chesi PIN eppudu veyavaddu.", "PIN veste dabbu radu; alanti QR scan cheyavaddu."],
    },
    "ta": {
        "otp": ["உங்கள் தொலைபேசிக்கு வந்த OTP ஐ யாரிடமும் சொல்ல வேண்டாம்.",
                "6 இலக்க OTP ஐ யாரிடமும் பகிர வேண்டாம்; வங்கி ஒருபோதும் கேட்காது."],
        "account_credentials": ["தெரியாத இணைப்புகளைச் சொடுக்கி உள்நுழைய வேண்டாம்.", "SMS இணைப்பில் கடவுச்சொல்லை உள்ளிட வேண்டாம்."],
        "funds": ["எங்கள் பெயரைச் சொல்பவருக்கு 4,500 ரூபாய் அனுப்ப வேண்டாம்.", "SMS இல் வந்த UPI ஐடிக்குப் பணம் அனுப்ப வேண்டாம்."],
        "none": ["இத்தகைய செய்திகளில் வரும் எண்ணை அழைக்க வேண்டாம்.", "அதிகாரி எனக் கூறும் தெரியாத எண்ணைத் தொடர்பு கொள்ள வேண்டாம்."],
        "device_control": ["யார் சொன்னாலும் AnyDesk ஐ நிறுவ வேண்டாம்.", "இணைப்பிலிருந்து செயலியைப் பதிவிறக்கி அணுகல் கொடுக்க வேண்டாம்."],
        "upi_pin": ["பணம் பெற QR ஐ ஸ்கேன் செய்து PIN ஒருபோதும் இட வேண்டாம்.", "PIN இட்டால் பணம் வராது; அத்தகைய QR ஐ ஸ்கேன் செய்ய வேண்டாம்."],
    },
    "kn": {
        "otp": ["ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಬಂದ OTP ಯಾರಿಗೂ ಹೇಳಬೇಡಿ.",
                "6 ಅಂಕಿಯ OTP ಯಾರಿಗೂ ಹಂಚಬೇಡಿ; ಬ್ಯಾಂಕ್ ಎಂದಿಗೂ ಕೇಳುವುದಿಲ್ಲ."],
        "account_credentials": ["ಅಪರಿಚಿತ ಲಿಂಕ್ ಕ್ಲಿಕ್ ಮಾಡಿ ಲಾಗಿನ್ ಮಾಡಬೇಡಿ.", "SMS ಲಿಂಕ್‌ನಲ್ಲಿ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಬೇಡಿ."],
        "funds": ["ನಮ್ಮ ಹೆಸರು ಹೇಳಿ ಕೇಳುವವರಿಗೆ 4,500 ರೂಪಾಯಿ ಕಳುಹಿಸಬೇಡಿ.", "SMS ನಲ್ಲಿ ಬಂದ UPI ಐಡಿಗೆ ಹಣ ಕಳುಹಿಸಬೇಡಿ."],
        "none": ["ಇಂತಹ ಸಂದೇಶಗಳಲ್ಲಿನ ಸಂಖ್ಯೆಗೆ ಕರೆ ಮಾಡಬೇಡಿ.", "ಅಧಿಕಾರಿ ಎಂದು ಹೇಳುವ ಅಪರಿಚಿತ ಸಂಖ್ಯೆಯನ್ನು ಸಂಪರ್ಕಿಸಬೇಡಿ."],
        "device_control": ["ಯಾರು ಹೇಳಿದರೂ AnyDesk ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಬೇಡಿ.", "ಲಿಂಕ್‌ನಿಂದ ಆ್ಯಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಪ್ರವೇಶ ಕೊಡಬೇಡಿ."],
        "upi_pin": ["ಹಣ ಪಡೆಯಲು QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ PIN ಎಂದಿಗೂ ಹಾಕಬೇಡಿ.", "PIN ಹಾಕಿದರೆ ಹಣ ಬರುವುದಿಲ್ಲ; ಅಂತಹ QR ಸ್ಕ್ಯಾನ್ ಮಾಡಬೇಡಿ."],
    },
    "cm_hi": {
        "otp": ["Phone par aaya OTP kisi ko share na karein.", "6-digit OTP kisi ko mat batayein; bank kabhi nahi maangta."],
        "account_credentials": ["Unknown link par click karke login mat karein.", "SMS link par password enter na karein."],
        "funds": ["Humara naam lekar maangne wale ko Rs 4,500 transfer na karein.", "SMS se mili UPI id par paise send na karein."],
        "none": ["Aise messages ke number par call mat karein.", "Officer batane wale unknown number par contact na karein."],
        "device_control": ["Kisi ke kehne par AnyDesk install na karein.", "Link se app download karke access mat dein."],
        "upi_pin": ["Paise receive karne ke liye QR scan karke PIN kabhi enter na karein.", "PIN daalne se paise nahi aate; aisa QR scan na karein."],
    },
    "cm_te": {
        "otp": ["Phone ki vachina OTP evariki share cheyakandi.", "6-digit OTP evariki cheppakandi; bank eppudu adagadu."],
        "account_credentials": ["Unknown link pai click chesi login cheyakandi.", "SMS link lo password enter cheyakandi."],
        "funds": ["Maa peru cheppi adige variki Rs 4,500 transfer cheyakandi.", "SMS lo vachina UPI id ki paisalu send cheyakandi."],
        "none": ["Ilanti messages lo ni number ki call cheyakandi.", "Officer ani cheppe unknown number ki contact cheyakandi."],
        "device_control": ["Evaru cheppina AnyDesk install cheyakandi.", "Link nunchi app download chesi access ivvakandi."],
        "upi_pin": ["Paisalu receive cheyadaniki QR scan chesi PIN eppudu enter cheyakandi.", "PIN veste paisalu raavu; alanti QR scan cheyakandi."],
    },
}

# Negated pretext, used so the flip is a *minimal* edit of the whole message.
NEGATED_PRETEXT = {
    "en": {"prefix": "Your account is safe and", "safety": "This is a safety advisory."},
    "hi": {"prefix": "आपका खाता सुरक्षित है और", "safety": "यह एक सुरक्षा सलाह है।"},
    "hi_Latn": {"prefix": "Aapka khata surakshit hai aur", "safety": "Yeh ek suraksha salah hai."},
    "te": {"prefix": "మీ ఖాతా సురక్షితం మరియు", "safety": "ఇది ఒక భద్రతా సలహా."},
    "te_Latn": {"prefix": "Mee khata surakshitam mariyu", "safety": "Idi oka bhadrata salaha."},
    "ta": {"prefix": "உங்கள் கணக்கு பாதுகாப்பாக உள்ளது மற்றும்", "safety": "இது ஒரு பாதுகாப்பு அறிவுரை."},
    "kn": {"prefix": "ನಿಮ್ಮ ಖಾತೆ ಸುರಕ್ಷಿತವಾಗಿದೆ ಮತ್ತು", "safety": "ಇದು ಒಂದು ಸುರಕ್ಷತಾ ಸಲಹೆ."},
    "cm_hi": {"prefix": "Aapka account safe hai aur", "safety": "Yeh ek safety advisory hai."},
    "cm_te": {"prefix": "Mee account safe ga undi mariyu", "safety": "Idi oka safety advisory."},
}

# ---------------------------------------------------------------------------
# HARD NEGATIVES: genuine messages that carry heavy scam vocabulary.
# ---------------------------------------------------------------------------
HARD_NEGATIVES = {
    "en": [
        "482913 is your OTP for login. Valid for 10 minutes. Do not share it with anyone.",
        "Rs 4,500.00 debited from A/c XX8821 on 14-Mar. Not you? Call 1800-111-222.",
        "Your KYC is complete. No further action is required from your side.",
        "Your parcel BX9931 was delivered at 4:12 PM. Thank you for shopping with us.",
        "Reminder: your electricity bill of Rs 1,240 is due on 28-Mar. Pay via the official app.",
        "We never ask for your OTP, PIN or CVV. Report suspicious calls to 1930.",
        "Your refund of Rs 4,999 has been credited to your original payment method.",
        "Congratulations on completing 5 years with us. No action needed.",
        "Your account statement for March is ready in the app. Login via the app only.",
        "Security alert: a login was attempted from a new device. If this was you, ignore this message.",
    ],
    "hi": [
        "482913 आपका लॉगिन ओटीपी है। 10 मिनट तक वैध। किसी को न बताएं।",
        "खाता XX8821 से 14-मार्च को 4,500 रुपये निकले। आपने नहीं? 1800-111-222 पर कॉल करें।",
        "आपका केवाईसी पूरा हो चुका है। आपको कुछ नहीं करना है।",
        "आपका पार्सल BX9931 शाम 4:12 बजे पहुंचा दिया गया। धन्यवाद।",
        "याद दिलाना: 1,240 रुपये का बिजली बिल 28-मार्च को देय है। आधिकारिक ऐप से भरें।",
        "हम कभी ओटीपी, पिन या सीवीवी नहीं मांगते। संदिग्ध कॉल की शिकायत 1930 पर करें।",
        "आपका 4,999 रुपये का रिफंड मूल भुगतान माध्यम में जमा कर दिया गया है।",
        "मार्च का खाता विवरण ऐप में तैयार है। केवल ऐप से लॉगिन करें।",
    ],
    "hi_Latn": [
        "482913 aapka login OTP hai. 10 minute tak valid. Kisi ko na batayein.",
        "Khata XX8821 se 14-March ko 4,500 rupaye nikle. Aapne nahi? 1800-111-222 par call karein.",
        "Aapka KYC poora ho chuka hai. Aapko kuch nahi karna hai.",
        "Aapka parcel BX9931 shaam 4:12 baje pahuncha diya gaya. Dhanyavad.",
        "Yaad dilana: 1,240 rupaye ka bijli bill 28-March ko dey hai. Adhikarik app se bharein.",
        "Hum kabhi OTP, PIN ya CVV nahi maangte. Sandigdh call ki shikayat 1930 par karein.",
        "Aapka 4,999 rupaye ka refund mool bhugtan madhyam mein jama kar diya gaya hai.",
        "March ka khata vivaran app mein taiyar hai. Keval app se login karein.",
    ],
    "te": [
        "482913 మీ లాగిన్ ఓటీపీ. 10 నిమిషాలు చెల్లుబాటు. ఎవరికీ చెప్పవద్దు.",
        "ఖాతా XX8821 నుండి 14-మార్చి న 4,500 రూపాయలు డెబిట్ అయ్యాయి. మీరు కాకపోతే 1800-111-222 కు కాల్ చేయండి.",
        "మీ కేవైసీ పూర్తయింది. మీరు ఏమీ చేయనవసరం లేదు.",
        "మీ పార్సెల్ BX9931 సాయంత్రం 4:12 కి డెలివరీ అయింది. ధన్యవాదాలు.",
        "గుర్తు చేస్తున్నాం: 1,240 రూపాయల కరెంటు బిల్లు 28-మార్చి కి చెల్లించాలి. అధికారిక యాప్ ద్వారా చెల్లించండి.",
        "మేము ఎప్పుడూ ఓటీపీ, పిన్ లేదా సీవీవీ అడగము. అనుమానాస్పద కాల్స్ 1930 కు ఫిర్యాదు చేయండి.",
        "మీ 4,999 రూపాయల రీఫండ్ అసలు చెల్లింపు విధానంలో జమ చేయబడింది.",
        "మార్చి ఖాతా వివరణ యాప్‌లో సిద్ధంగా ఉంది. యాప్ ద్వారా మాత్రమే లాగిన్ అవ్వండి.",
    ],
    "te_Latn": [
        "482913 mee login OTP. 10 nimishalu chellubatu. Evariki cheppavaddu.",
        "Khata XX8821 nunchi 14-March na 4,500 rupayalu debit ayyayi. Meeru kakapote 1800-111-222 ku call cheyandi.",
        "Mee KYC poorthayindi. Meeru emi cheyanavasaram ledu.",
        "Mee parcel BX9931 sayantram 4:12 ki delivery ayindi. Dhanyavadalu.",
        "Gurtu chestunnam: 1,240 rupayala currentu billu 28-March ki chellinchali. Adhikarika app dvara chellinchandi.",
        "Memu eppudu OTP, PIN leda CVV adagamu. Anumanaspada calls 1930 ku firyadu cheyandi.",
        "Mee 4,999 rupayala refund asalu chellimpu vidhanamlo jama cheyabadindi.",
        "March khata vivarana app lo siddhanga undi. App dvara matrame login avvandi.",
    ],
    "ta": [
        "482913 உங்கள் உள்நுழைவு OTP. 10 நிமிடங்களுக்கு செல்லுபடியாகும். யாரிடமும் பகிர வேண்டாம்.",
        "கணக்கு XX8821 இலிருந்து 14-மார்ச் அன்று 4,500 ரூபாய் எடுக்கப்பட்டது. நீங்கள் இல்லையா? 1800-111-222 ஐ அழைக்கவும்.",
        "உங்கள் கேஒய்சி முடிந்தது. உங்கள் தரப்பில் எந்த நடவடிக்கையும் தேவையில்லை.",
        "உங்கள் பார்சல் BX9931 மாலை 4:12 மணிக்கு வழங்கப்பட்டது. நன்றி.",
        "நினைவூட்டல்: 1,240 ரூபாய் மின் கட்டணம் 28-மார்ச் அன்று செலுத்த வேண்டும். அதிகாரப்பூர்வ செயலி வழியாக செலுத்தவும்.",
        "நாங்கள் ஒருபோதும் OTP, PIN அல்லது CVV கேட்பதில்லை. சந்தேகமான அழைப்புகளை 1930 இல் புகாரளிக்கவும்.",
        "உங்கள் 4,999 ரூபாய் பணத்திரும்பம் அசல் கட்டண முறையில் வரவு வைக்கப்பட்டுள்ளது.",
    ],
    "kn": [
        "482913 ನಿಮ್ಮ ಲಾಗಿನ್ OTP. 10 ನಿಮಿಷ ಮಾನ್ಯ. ಯಾರಿಗೂ ಹಂಚಬೇಡಿ.",
        "ಖಾತೆ XX8821 ರಿಂದ 14-ಮಾರ್ಚ್ ರಂದು 4,500 ರೂಪಾಯಿ ಡೆಬಿಟ್ ಆಗಿದೆ. ನೀವಲ್ಲವೇ? 1800-111-222 ಗೆ ಕರೆ ಮಾಡಿ.",
        "ನಿಮ್ಮ ಕೆವೈಸಿ ಪೂರ್ಣಗೊಂಡಿದೆ. ನಿಮ್ಮ ಕಡೆಯಿಂದ ಯಾವುದೇ ಕ್ರಮ ಅಗತ್ಯವಿಲ್ಲ.",
        "ನಿಮ್ಮ ಪಾರ್ಸೆಲ್ BX9931 ಸಂಜೆ 4:12 ಕ್ಕೆ ತಲುಪಿಸಲಾಗಿದೆ. ಧನ್ಯವಾದಗಳು.",
        "ಜ್ಞಾಪನೆ: 1,240 ರೂಪಾಯಿ ವಿದ್ಯುತ್ ಬಿಲ್ 28-ಮಾರ್ಚ್ ಗೆ ಪಾವತಿಸಬೇಕು. ಅಧಿಕೃತ ಆ್ಯಪ್ ಮೂಲಕ ಪಾವತಿಸಿ.",
        "ನಾವು ಎಂದಿಗೂ OTP, PIN ಅಥವಾ CVV ಕೇಳುವುದಿಲ್ಲ. ಸಂಶಯಾಸ್ಪದ ಕರೆಗಳನ್ನು 1930 ಗೆ ವರದಿ ಮಾಡಿ.",
        "ನಿಮ್ಮ 4,999 ರೂಪಾಯಿ ಮರುಪಾವತಿ ಮೂಲ ಪಾವತಿ ವಿಧಾನಕ್ಕೆ ಜಮಾ ಆಗಿದೆ.",
    ],
    "cm_hi": [
        "482913 aapka login OTP hai. 10 min valid. Kisi ke saath share na karein.",
        "Rs 4,500 debit from A/c XX8821 on 14-Mar. Aapne nahi kiya? 1800-111-222 par call karein.",
        "Aapka KYC complete ho gaya hai. Koi action required nahi hai.",
        "Aapka parcel BX9931 4:12 PM par deliver ho gaya. Thank you.",
        "Reminder: Rs 1,240 ka electricity bill 28-Mar ko due hai. Official app se pay karein.",
        "Hum kabhi OTP, PIN ya CVV nahi maangte. Suspicious calls 1930 par report karein.",
    ],
    "cm_te": [
        "482913 mee login OTP. 10 min valid. Evariki share cheyakandi.",
        "Rs 4,500 debit from A/c XX8821 on 14-Mar. Meeru cheyakapote 1800-111-222 ki call cheyandi.",
        "Mee KYC complete ayindi. Elanti action avasaram ledu.",
        "Mee parcel BX9931 4:12 PM ki deliver ayindi. Thank you.",
        "Reminder: Rs 1,240 electricity bill 28-Mar ki due undi. Official app dvara pay cheyandi.",
        "Memu eppudu OTP, PIN leda CVV adagamu. Suspicious calls 1930 ki report cheyandi.",
    ],
}


# ---------------------------------------------------------------------------
# GENERIC BENIGN messages: ordinary traffic with little or no scam vocabulary.
# These exist so that the training distribution is class-balanced and a
# degenerate "always predict attack" classifier cannot score well.
# ---------------------------------------------------------------------------
BENIGN_GENERIC = {
    "en": [
        "Your order has been shipped and will arrive by Friday.",
        "Table for four is confirmed for 8 PM tonight. See you soon.",
        "Class timetable for next semester is now available on the portal.",
        "Your appointment with Dr Rao is rescheduled to Tuesday 11 AM.",
        "Thanks for your payment. Your subscription renews on 12 April.",
        "The library book you reserved is ready for collection.",
        "Match starts at 7:30. Reaching the ground by 7, come directly.",
        "Your cab is arriving in 3 minutes. Driver: Suresh, KA01AB1234.",
        "Monthly team review moved to Thursday. Agenda attached in email.",
        "Power maintenance in your area on Sunday 9 AM to 1 PM.",
    ],
    "hi": [
        "आपका ऑर्डर भेज दिया गया है और शुक्रवार तक पहुंच जाएगा।",
        "आज रात 8 बजे चार लोगों की टेबल बुक है। मिलते हैं।",
        "अगले सेमेस्टर की समय सारिणी पोर्टल पर उपलब्ध है।",
        "डॉ राव के साथ आपकी अपॉइंटमेंट मंगलवार 11 बजे हो गई है।",
        "भुगतान के लिए धन्यवाद। आपकी सदस्यता 12 अप्रैल को नवीनीकृत होगी।",
        "आपकी आरक्षित पुस्तकालय पुस्तक तैयार है।",
        "मैच 7:30 पर शुरू होगा। मैं 7 बजे मैदान पहुंच रहा हूँ।",
        "रविवार सुबह 9 से 1 बजे तक आपके क्षेत्र में बिजली रखरखाव होगा।",
    ],
    "hi_Latn": [
        "Aapka order bhej diya gaya hai aur shukrawar tak pahunch jayega.",
        "Aaj raat 8 baje chaar logon ki table book hai. Milte hain.",
        "Agle semester ki samay sarini portal par uplabdh hai.",
        "Dr Rao ke saath aapki appointment mangalwar 11 baje ho gayi hai.",
        "Bhugtan ke liye dhanyavad. Aapki sadasyata 12 April ko navinikrit hogi.",
        "Aapki aarakshit pustakalay pustak taiyar hai.",
        "Match 7:30 par shuru hoga. Main 7 baje maidan pahunch raha hoon.",
        "Ravivar subah 9 se 1 baje tak aapke kshetra mein bijli rakhrakhav hoga.",
    ],
    "te": [
        "మీ ఆర్డర్ పంపబడింది, శుక్రవారం నాటికి చేరుతుంది.",
        "ఈ రాత్రి 8 గంటలకు నలుగురికి టేబుల్ బుక్ అయింది. కలుద్దాం.",
        "వచ్చే సెమిస్టర్ టైమ్ టేబుల్ పోర్టల్‌లో అందుబాటులో ఉంది.",
        "డాక్టర్ రావు గారితో మీ అపాయింట్‌మెంట్ మంగళవారం 11 గంటలకు మారింది.",
        "చెల్లింపునకు ధన్యవాదాలు. మీ సభ్యత్వం ఏప్రిల్ 12 న పునరుద్ధరించబడుతుంది.",
        "మీరు రిజర్వ్ చేసిన లైబ్రరీ పుస్తకం సిద్ధంగా ఉంది.",
        "మ్యాచ్ 7:30 కి మొదలవుతుంది. నేను 7 కి గ్రౌండ్‌కు చేరుకుంటాను.",
        "ఆదివారం ఉదయం 9 నుండి 1 వరకు మీ ప్రాంతంలో విద్యుత్ నిర్వహణ ఉంటుంది.",
    ],
    "te_Latn": [
        "Mee order pampabadindi, shukravaram natiki cherutundi.",
        "Ee ratri 8 gantalaku naluguriki table book ayindi. Kaluddam.",
        "Vachche semester time table portal lo andubatulo undi.",
        "Doctor Rao garito mee appointment mangalavaram 11 gantalaku marindi.",
        "Chellimpunaku dhanyavadalu. Mee sabhyatvam April 12 na punaruddharinchabadutundi.",
        "Meeru reserve chesina library pustakam siddhanga undi.",
        "Match 7:30 ki modalavutundi. Nenu 7 ki ground ku cherukuntanu.",
        "Adivaram udayam 9 nunchi 1 varaku mee prantamlo vidyut nirvahana untundi.",
    ],
    "ta": [
        "உங்கள் ஆர்டர் அனுப்பப்பட்டது, வெள்ளிக்கிழமைக்குள் வந்துவிடும்.",
        "இன்றிரவு 8 மணிக்கு நான்கு பேருக்கு மேஜை பதிவு செய்யப்பட்டது.",
        "அடுத்த பருவத்தின் கால அட்டவணை போர்ட்டலில் கிடைக்கிறது.",
        "டாக்டர் ராவ் உடனான உங்கள் சந்திப்பு செவ்வாய் 11 மணிக்கு மாற்றப்பட்டது.",
        "கட்டணத்திற்கு நன்றி. உங்கள் சந்தா ஏப்ரல் 12 அன்று புதுப்பிக்கப்படும்.",
        "நீங்கள் பதிவு செய்த நூலக புத்தகம் தயாராக உள்ளது.",
        "ஆட்டம் 7:30 க்கு தொடங்கும். நான் 7 மணிக்கு மைதானம் வருகிறேன்.",
        "ஞாயிறு காலை 9 முதல் 1 வரை உங்கள் பகுதியில் மின் பராமரிப்பு நடக்கும்.",
    ],
    "kn": [
        "ನಿಮ್ಮ ಆರ್ಡರ್ ಕಳುಹಿಸಲಾಗಿದೆ, ಶುಕ್ರವಾರದೊಳಗೆ ತಲುಪುತ್ತದೆ.",
        "ಇಂದು ರಾತ್ರಿ 8 ಗಂಟೆಗೆ ನಾಲ್ವರಿಗೆ ಟೇಬಲ್ ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
        "ಮುಂದಿನ ಸೆಮಿಸ್ಟರ್ ವೇಳಾಪಟ್ಟಿ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಲಭ್ಯವಿದೆ.",
        "ಡಾ. ರಾವ್ ಅವರೊಂದಿಗಿನ ನಿಮ್ಮ ಭೇಟಿ ಮಂಗಳವಾರ 11 ಗಂಟೆಗೆ ಬದಲಾಗಿದೆ.",
        "ಪಾವತಿಗೆ ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ಚಂದಾದಾರಿಕೆ ಏಪ್ರಿಲ್ 12 ರಂದು ನವೀಕರಣಗೊಳ್ಳುತ್ತದೆ.",
        "ನೀವು ಕಾಯ್ದಿರಿಸಿದ ಗ್ರಂಥಾಲಯ ಪುಸ್ತಕ ಸಿದ್ಧವಾಗಿದೆ.",
        "ಪಂದ್ಯ 7:30 ಕ್ಕೆ ಆರಂಭವಾಗುತ್ತದೆ. ನಾನು 7 ಗಂಟೆಗೆ ಮೈದಾನಕ್ಕೆ ಬರುತ್ತೇನೆ.",
        "ಭಾನುವಾರ ಬೆಳಿಗ್ಗೆ 9 ರಿಂದ 1 ರವರೆಗೆ ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ವಿದ್ಯುತ್ ನಿರ್ವಹಣೆ ಇರುತ್ತದೆ.",
    ],
    "cm_hi": [
        "Aapka order ship ho gaya hai, Friday tak aa jayega.",
        "Aaj raat 8 baje 4 logon ki table book hai. Milte hain.",
        "Next semester ka timetable portal par available hai.",
        "Dr Rao ke saath appointment Tuesday 11 AM shift ho gaya.",
        "Payment ke liye thanks. Subscription 12 April ko renew hoga.",
        "Library book ready hai, collect kar lijiye.",
        "Match 7:30 par start hoga, main 7 baje ground pahunch raha hoon.",
        "Sunday 9 AM se 1 PM tak area mein power maintenance hai.",
    ],
    "cm_te": [
        "Mee order ship ayindi, Friday ki vastundi.",
        "Ee ratri 8 gantalaki 4 mandiki table book ayindi. Kaluddam.",
        "Next semester timetable portal lo available undi.",
        "Dr Rao tho appointment Tuesday 11 AM ki shift ayindi.",
        "Payment ki thanks. Subscription April 12 na renew avutundi.",
        "Library book ready ga undi, collect chesukondi.",
        "Match 7:30 ki start avutundi, nenu 7 ki ground ki vastanu.",
        "Sunday 9 AM nunchi 1 PM varaku area lo power maintenance undi.",
    ],
}
